### ISSUE TITLE
Content images

### ISSUE THREAD

**Issue by deleuterio** [lern-edu/lern#100]
- Qual o tipo de usuário ou beneficiado (própria equipe/admin/teacher/users...)
Developers e admins

- Breve história da issue
Eu como administrador quero vincular imagens em um conteúdo qualquer.

- Definition of done
- [x] Upload S3 AWS
- [x] Campo para upload de imagem
- [x] campo no schema content
- [x] template de exibição

usar projeto anterior como base:
https://github.com/lern-edu/lern-app/tree/develop/client/views/Public/Misc/Content

**Comment by andredornas** [comment]
@deleuterio @dantenol o que voces acham sobre deixar o bucket de imagens publico? fica mais facil para mostrar a imagem, maaas segurança....

**Comment by deleuterio** [comment]
Man, pode deixar público a leitura e a escrita será definida pela key do que criamos ela tem full access no bucket e nossa aplicação usa ela para fazer uploads no server side.
