### ISSUE TITLE
Content Youtube

### ISSUE THREAD

**Issue by deleuterio** [lern-edu/lern#101]
## Incorporar vídeos Youtube
- Qual o tipo de usuário ou beneficiado (própria equipe/admin/teacher/users...)
Admins

- Breve história da issue
Eu como administrador quer inserir vídeos do youtube em qualquer conteúdo

- Definition of done
- [x] criar field no Content para vídeo
- [x] template para inserir vídeo
- [x] template para mostrar vídeo
- [ ] lógica para buscar vídeo

Usar packages e telas do projeto anterior:
- https://github.com/lern-edu/lern-app/tree/develop/packages/youtube-api
- https://github.com/lern-edu/lern-app/tree/develop/client/views/Public/Misc/Content

**Comment by andredornas** [comment]
@deleuterio lógica para buscar vídeo é pesquisar pelo nome e aparecer uma lista de videos, certo?

**Comment by deleuterio** [comment]
@andredornas não não, é mais simples, é apartir de uma url com o id do vídeo buscar o embed do youtube, nome e (thumbnail talvez).

**Comment by deleuterio** [comment]
Isso é só para exibir para o student.

**Comment by andredornas** [comment]
Valeu!
