### ISSUE TITLE
Sudoku test

### ISSUE THREAD

**Issue by deleuterio** [lern-edu/lern#106]
## Vincular sudoku a um teste

- Qual o tipo de usuário ou beneficiado (própria equipe/admin/teacher/users...)
Admins e students

- Breve história da issue
Eu como administrador quero vincular um sudoku a um teste/tarefa

- Definition of done
- [ ] habilitar essa possibilidade em um teste
- [ ] retornar acertividade do sudoku ao terminar
- [ ] permitir verificar se o jogo está correto antes de submit

**Comment by deleuterio** [comment]
Vou criar a view de exibição de conteúdo também.

**Comment by andredornas** [comment]
@deleuterio repara que ja criei um branch pra essa issue, com um package pros jogos

**Comment by deleuterio** [comment]
Ótimo! vou mergir no branch dessa issue!
