### ISSUE TITLE
Tags dialog

### ISSUE THREAD

**Issue by deleuterio** [lern-edu/lern#107]
Dialog com content da tag

- Qual o tipo de usuário ou beneficiado (própria equipe/admin/teacher/users...)
student

- Breve história da issue
Eu como estudante quero ver qual o significado da competência do meu exercício ou relatório

- Definition of done
- [x] dialog que ocupa toda tela
- [x] exibir conteúdo
- [x] toolbar com nome da tag e opção de voltar

**Comment by andredornas** [comment]
Ainda nao temos o display de tags para o student. Criei um template nas tags com um Dialog.
