### ISSUE TITLE
Atualizar react 16.2.0

### ISSUE THREAD

**Issue by deleuterio** [lern-edu/lern#11]
## Update de package para usufruir de vantagens da nova versão
- Qual o tipo de usuário ou beneficiado (própria equipe/admin/teacher/users...)
Developers

- Breve história da issue
Apenas atualização de package

- Definition of done

- [x] Atualizar [React](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html)
- [x] Instalação [Babel](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-jsx#pragmafrag)

**Comment by dantenol** [comment]
Babel-transform-jsx não compila fragmentos do react 16.2

**Comment by dantenol** [comment]
https://github.com/meteor/react-packages/issues/241
