### ISSUE TITLE
Error on RichText

### ISSUE THREAD

**Issue by andredornas** [lern-edu/lern#114]
## <Breve identificação do que fazer>

- Qual o tipo de usuário ou beneficiado (própria equipe/admin/teacher/users...)
equipe
- Breve história da issue
Algumas vezes ao salvar o seguinte erro acontece:
![image.png](https://images.zenhubusercontent.com/57ec087f95e42b6c5ba998e9/3e8f67e6-7882-48c3-9cc0-716b5ca6e859)
- Definition of done

**Comment by andredornas** [comment]
Quando salva depois de editar o campo type nao é inserido no content no banco.
![image](https://user-images.githubusercontent.com/11529613/36753082-def31d9a-1be3-11e8-9cb2-93f378923a8b.png)

**Comment by andredornas** [comment]
@deleuterio nao sei o que ta acontecendo, o doc que vai pra salvar ta completinho, mas não salva alguns campos do content

**Comment by deleuterio** [comment]
Ainda não descobri direito qual o erro, mas é em manipular array no astronomy.

**Comment by andredornas** [comment]
Mas conseguiu reproduzir aí? Só acontece quando vai editar...

**Comment by deleuterio** [comment]
Parece que o problema é deixar o type de um content como immutable... :thinking:
