### ISSUE TITLE
Video search error

### ISSUE THREAD

**Issue by deleuterio** [lern-edu/lern#122]
## Problemas ao pesquisar vídeo

![Selection_121.png](https://images.zenhubusercontent.com/58387800b9dc3c622022819d/4ec06f83-1ca9-4eb4-829d-fa35ed316575)

**Comment by andredornas** [comment]
nao consegui reproduzir, como aconteceu?

**Comment by deleuterio** [comment]
Hum, pode ser minha chave de api então... se puder me mandar via gist ou slack sua chave por favor

**Comment by deleuterio** [comment]
Meu IP que mudou há tempos e ele está bloqueado.
