### ISSUE TITLE
login methods fails

### ISSUE THREAD

**Issue by deleuterio** [lern-edu/lern#130]
- handle redirect no mobile app não funciona em alguns casos
- rota de login quando estiver logado tem que redirecionar para home
- handle redirect do face tbm não funciona em alguns casos

testar meteor como app android! é fácil isso:
`meteor --port 3000 --settings settings.json run android-device`

**Comment by andredornas** [comment]
@deleuterio viu esse warning? 

WARNING: It looks like you are using OAuth2 login in your app. Meteor's OAuth2 implementation does not
         currently work with mobile apps in local development mode, except in the iOS simulator. You can
         run the iOS simulator with 'meteor run ios'. For additional workarounds, see
         https://github.com/meteor/meteor/wiki/OAuth-for-mobile-Meteor-clients.

**Comment by deleuterio** [comment]
Vi sim man, mas nem consegui rodar o app remotamente ai nem me importei...

**Comment by deleuterio** [comment]
https://github.com/lern-edu/lern/wiki/FAQ#login-does-nothing
