### ISSUE TITLE
app bar receive a component children on left

### ISSUE THREAD

**Issue by deleuterio** [lern-edu/lern#133]
- app bar com opções de mostrar descrição da tarefa e ajuda

**Comment by andredornas** [comment]
@deleuterio rola de especificar melhor essa issue? sahusahusa é pra colocar icone na appbar?

**Comment by deleuterio** [comment]
É isso mesmo man, vou fazer um mockup pra isso.

**Comment by deleuterio** [comment]
![appbar](https://user-images.githubusercontent.com/12951402/38083657-9c71cbfc-3320-11e8-89fe-c7eb4a3c95dc.png)
A tela não importa tanto, mas no AppBar que está no package de Layouts quero possibilitar de passar um children como este do mockup.

**Comment by deleuterio** [comment]
Na tela de tarefas os requisitos são os seguintes:
- [x] Opção para abrir dialog com descrição do teste
- [x] Opção para abrir ajuda do teste (se houver)
- [x] Divider
- [x] Opção para habilitar e desabilitar highlight de sudoku se for um sudoku
![list](https://user-images.githubusercontent.com/12951402/38083952-7926a69e-3321-11e8-8660-3d18b3170982.jpg)
