### ISSUE TITLE
enrolment screen

### ISSUE THREAD

**Issue by deleuterio** [lern-edu/lern#149]
## Tela de cadastro de usuário por email
- Qual o tipo de usuário ou beneficiado (própria equipe/admin/teacher/users...)
Student

- Breve história da issue
No usuário estudante quero me cadastrar na plataforma com meu email sem precisar de um admin

- Definition of done
- [x] Form de cadastro
- [x] Primeiro login tem que preencher os campos:
   - [x] Primeiro Nome
   - [x] Sobrenome
   - [x] Língua
   - [x] Password (já é a tela de enrolment normal)

**Comment by andredornas** [comment]
@deleuterio como seria o acesso à tela de login?
