### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by deleuterio** [lern-edu/lern#160]
## Definir timeouts global e por página
- Qual o tipo de usuário ou beneficiado (própria equipe/admin/teacher/users...)
Admin
- Breve história da issue
Sendo um administrador quero definir um timeout para uma página ou teste e ao final do timeout eu vou para a próxima página ou encerro o teste.

- Definition of done
- [x] campos para setar timeout page e global
- [x] timeout aparecendo no bottom bar do TestAttempt
- [x] comportamento ao timeout qualquer

### Requisitos
- [x] Usuário não pode ter um botão para voltar
Cenários abaixo para caso a internet caia ou o usuário feche o navegador
- [x] Ao sair do teste o tempo continua correndo... acho que podemos definir uma cron para encerrar o teste quando ele começa o attempt, isso para test timeout global
- [x] se o timeout for por pages, aqui também pode ter uma cron com a soma de timeouts
![bottom](https://user-images.githubusercontent.com/12951402/38084503-7d4e4ef0-3323-11e8-966e-682bce2ef197.jpg)

### Description
Esse tipo de timeout é o que encerra o teste, tiferente do timerange que serve na hora do cálculo da pontuação.

Exemplo 1:
- Defino tipo de timeout como global
- tempo de timeout é 3600 segundos
- o teste tem várias páginas
Output:
- Bottom bar tem cronômetro com tempo de 1h
- Aluno pode passear por todas as páginas durante esse tempo para resolver o teste

Exemplo 1:
- Defino tipo de timeout como pages
- o teste tem várias páginas
- página 1 o timeout é 60 segundos
- página 2 o timeout é 30 segundos
Output:
- Bottom bar tem cronômetro com tempo de 60 segundos
- Aluno fica preso nessa página até o tempo acabar ou responder
- ao ir para próxima página o timeout passa a ser 30 segundos
- Aluno fica preso nessa página até o tempo acabar ou responder

**Comment by andredornas** [comment]
@deleuterio o que é o timeType? uma opçao é range e aoutra?

**Comment by deleuterio** [comment]
@andredornas o time.type é pra definir se o timeout será por página ou para todo o teste.
`[pages, global, none]`

**Comment by andredornas** [comment]
@deleuterio e o outro? no static.js ta assim:

`TestTimeoutTypes: ['global', 'none'],
  TestTimeTypes: ['range', 'none'],`

nesse do range seria o que outra opção?

**Comment by deleuterio** [comment]
Exatamente. Um para avaliação e outro para timeout.

**Comment by andredornas** [comment]
acho que saquei... vou mexer auqi e qualquer coisa te chamo, vlwws

**Comment by andredornas** [comment]
- inserir possibilidade de sair do teste e voltar (continuando o cronômetro) ou de não deixar 
- inserir startedAt e finishedAt em cada página -> serve para timeout por página e também para analytics

**Comment by andredornas** [comment]
@deleuterio se o teste é cronometrado, o cara pode voltar paginas?

**Comment by deleuterio** [comment]
Só pode voltar página se o cronometro for global 🌐 @andredornas

**Comment by deleuterio** [comment]
@andredornas Estou trabalhando nesses detalhes aqui... Você já trabalhou :smiley:
