### ISSUE TITLE
Http error on production

### ISSUE THREAD

**Issue by andredornas** [lern-edu/lern#162]
## <Breve identificação do que fazer>

- Qual o tipo de usuário ou beneficiado (própria equipe/admin/teacher/users...)

- Breve história da issue
![image.png](https://images.zenhubusercontent.com/57ec087f95e42b6c5ba998e9/7a66a578-eeff-4dfb-b297-4b77614154b1)
- Definition of done

**Comment by andredornas** [comment]
tem que setar a ROOT_URL no settings.json com a url https

https://github.com/apollographql/meteor-integration/issues/98

**Comment by andredornas** [comment]
![image](https://user-images.githubusercontent.com/11529613/38399401-9817f882-3920-11e8-83cf-c3aff1c8c33e.png)

**Comment by andredornas** [comment]
@deleuterio em production, roda o npm start mesmo?

**Comment by deleuterio** [comment]
Nops, uso phusion-passager + nginx para deploy. Isso ai não é muita prioriadade, o problema é cors mesmo... Por causa dos locales.

**Comment by andredornas** [comment]
Ou, mas o problema de cors é que o i18n, na hora de gerar a url, ele usa esse Meteor.absoluteUrl(). Aí essa função pega do ROOT_URL... como mandei no print ai, as URLs tão vindo com HTTP, se definir a ROOT_URL com HTTPS, resolveria o problema de cors

**Comment by deleuterio** [comment]
Ah, então fechou! Pode só mudar no package mesmo. Acho que não tem como mudar em tempo de execução né?

**Comment by deleuterio** [comment]
Olhei aqui parece que pode ser setado no settings.json:
https://galaxy-guide.meteor.com/environment-variables.html

**Comment by andredornas** [comment]
Não sei.. porque se ele rodar o npm start em production, definir a root_url
como https://app.lern.com.br, não sei se vai afetar o localhost

Em sex, 6 de abr de 2018 09:06, Douglas Eleutério Alves <
notifications@github.com> escreveu:

**Comment by deleuterio** [comment]
Ah acho que vai interferir não, vamos mandar bala nesse trem.
