### ISSUE TITLE
Documentação dos métodos de usuários

### ISSUE THREAD

**Issue by deleuterio** [lern-edu/lern#17]
## Documentação lern-methods/admin/users

- Qual o tipo de usuário ou beneficiado (própria equipe/admin/teacher/users...)
Developers

- Breve história da issue
Usar jsdoc para criar documentação de cada um dos métodos
Criar namespace para package e para o grupo admin de methods.

- Definition of done
- [ ] Criar namespace para lern-methods
- [ ] Criar namespace para Admin dentro de lern-methods
- [ ] Documentar os métodos que tenha a palavra `'User'`

**Comment by Fragador** [comment]
issue feita por @andredornas issue: https://github.com/lern-edu/lern/issues/30
