### ISSUE TITLE
Teste de unidade Check

### ISSUE THREAD

**Issue by deleuterio** [lern-edu/lern#18]
## Teste de unidade package lern-check

- Qual o tipo de usuário ou beneficiado (própria equipe/admin/teacher/users...)
Developers

- Breve história da issue
Testes de unidade para cada um dos checks do package
*tem um erro ao usar o método `Accounts.createUser` por isso não terminei*

- Definition of done
- [x] Testes de unidade para checks de Cursor
- [x] Testes de unidade para checks de User
- [x] Testes de unidade para checks de Regex

**Comment by andredornas** [comment]
Error: Accounts.createUser is not a function

**Comment by andredornas** [comment]
Resolvido com a adição do package accounts-password no test do package lern-check
