### ISSUE TITLE
Request Email on Register

### ISSUE THREAD

**Issue by deleuterio** [lern-edu/lern#78]
## Autenticação requerir email

- Qual o tipo de usuário ou beneficiado (própria equipe/admin/teacher/users...)
Users

- Breve história da issue
Eu ao cadastrar preciso colocar email mesmo com retorno de redes sociais sem esse campo.

- Definition of done

**Comment by andredornas** [comment]
@lern-edu/developers quero a opinião de voces pra esse tópico. 
Tentei muito aqui e acho que não é possível abrir um dialog quando o login do facebook ou google não retornam um email, pedir pro usuario escrever o email e continuar com a requisicao de login pelo facebook. 

- O que eu pensei: criar uma tela after login e before all para o usuario escrever o email que falta.
- Como: o login social,, mesmo sem email, vai ser um sucesso e, na Meteor.call da rota inicial do usuario, confiro se o email existe ou nao, redirecionando para uma pagina extra caso negativo.
- O problema: nessa nova página (ex: '/complete'), se o usuario mudar pra /student, ele consegue navegar corretamente.
- Uma POSSÍVEL soluçao (se necessario): conferir no Safe se os emails existem.

O que acham??

**Comment by deleuterio** [comment]
Perfeito! A saída que ia propor era justamente de verificar no safe se ele possui um email, se não possuir sempre redireciono ele para a tela de finalizar cadastro.
