### ISSUE TITLE
Mergir usuário no login usando redes sociais

### ISSUE THREAD

**Issue by andredornas** [lern-edu/lern#83]
## Login mergir documentos do usuário

- Qual o tipo de usuário ou beneficiado (própria equipe/admin/teacher/users...)
equipe

- Breve história da issue
Ao cadastrar usando as redes sociais, os documentos do mongo devem ser fundidos, de forma a não manter vários documentos que são do mesmo usuário.

- Definition of done
- [ ] Logar nas redes sociais e com o email não duplicar os documentos no mongo

**Comment by andredornas** [comment]
@deleuterio https://github.com/lirbank/meteor-accounts-merge o que acha?

UPDATE: esquece, melhor conferir na mão no hook de login

**Comment by deleuterio** [comment]
Haha de boa! :trollface:
